"""Fidelity evaluation, quality gates, and canonical verification models (Stage 9A / 9B / 9C)."""
from fidelity.evaluator import FidelityEvaluator, validate_consumer_gate
from fidelity.models import (
    BoundChromiumEvidence,
    BoundFontToolsEvidence,
    BoundFreeTypeEvidence,
    BoundHarfBuzzEvidence,
    ChromiumGlyphSampleEvidence,
    ChromiumPairSampleEvidence,
    ConsumerEvidenceBundle,
    ConsumerGateResult,
    CoverageGateResult,
    FidelityReport,
    FidelityThresholds,
    FreeTypeSampleEvidence,
    GeometryRasterGateResult,
    HarfBuzzPositionVector,
    HarfBuzzSampleEvidence,
    MetricsGateResult,
    ProductionProducerError,
    TopologyGateResult,
    TypographyGateResult,
)
from fidelity.pipeline import (
    LocalFidelityIntegrationPipeline,
    LocalFidelityPipelineResult,
    ObservationStoreSnapshot,
    PartitionedEvidence,
    partition_snapshot,
)
from fidelity.producers import (
    CandidateArtifact,
    CandidateArtifactDescriptor,
    ChromiumEvidenceProducer,
    FontToolsEvidenceProducer,
    FreeTypeEvidenceProducer,
    HarfBuzzEvidenceProducer,
    ProductionConsumerEvidenceProducer,
)

__all__ = [
    "BoundChromiumEvidence",
    "BoundFontToolsEvidence",
    "BoundFreeTypeEvidence",
    "BoundHarfBuzzEvidence",
    "CandidateArtifact",
    "CandidateArtifactDescriptor",
    "ChromiumEvidenceProducer",
    "ChromiumGlyphSampleEvidence",
    "ChromiumPairSampleEvidence",
    "ConsumerEvidenceBundle",
    "ConsumerGateResult",
    "CoverageGateResult",
    "FidelityEvaluator",
    "FidelityReport",
    "FidelityThresholds",
    "FontToolsEvidenceProducer",
    "FreeTypeEvidenceProducer",
    "FreeTypeSampleEvidence",
    "GeometryRasterGateResult",
    "HarfBuzzEvidenceProducer",
    "HarfBuzzPositionVector",
    "HarfBuzzSampleEvidence",
    "LocalFidelityIntegrationPipeline",
    "LocalFidelityPipelineResult",
    "MetricsGateResult",
    "ObservationStoreSnapshot",
    "PartitionedEvidence",
    "ProductionConsumerEvidenceProducer",
    "ProductionProducerError",
    "TopologyGateResult",
    "TypographyGateResult",
    "partition_snapshot",
    "validate_consumer_gate",
]
