"""Fidelity evaluation, quality gates, and canonical verification models (Stage 9A / 9B)."""
from fidelity.evaluator import FidelityEvaluator
from fidelity.models import (
    BoundChromiumEvidence,
    BoundFontToolsEvidence,
    BoundFreeTypeEvidence,
    BoundHarfBuzzEvidence,
    ChromiumGlyphSampleEvidence,
    ChromiumPairSampleEvidence,
    ConsumerEvidenceBundle,
    ConsumerGateResult,
    CoverageGateResult,
    FidelityReport,
    FidelityThresholds,
    FreeTypeSampleEvidence,
    GeometryRasterGateResult,
    HarfBuzzSampleEvidence,
    MetricsGateResult,
    TopologyGateResult,
    TypographyGateResult,
)
from fidelity.producers import (
    CandidateArtifact,
    CandidateArtifactDescriptor,
    ChromiumEvidenceProducer,
    FontToolsEvidenceProducer,
    FreeTypeEvidenceProducer,
    HarfBuzzEvidenceProducer,
    ProductionConsumerEvidenceProducer,
)

__all__ = [
    "BoundChromiumEvidence",
    "BoundFontToolsEvidence",
    "BoundFreeTypeEvidence",
    "BoundHarfBuzzEvidence",
    "CandidateArtifact",
    "CandidateArtifactDescriptor",
    "ChromiumEvidenceProducer",
    "ChromiumGlyphSampleEvidence",
    "ChromiumPairSampleEvidence",
    "ConsumerEvidenceBundle",
    "ConsumerGateResult",
    "CoverageGateResult",
    "FidelityEvaluator",
    "FidelityReport",
    "FidelityThresholds",
    "FontToolsEvidenceProducer",
    "FreeTypeEvidenceProducer",
    "FreeTypeSampleEvidence",
    "GeometryRasterGateResult",
    "HarfBuzzEvidenceProducer",
    "HarfBuzzSampleEvidence",
    "MetricsGateResult",
    "ProductionConsumerEvidenceProducer",
    "TopologyGateResult",
    "TypographyGateResult",
]
